### ISSUE TITLE
acp won't build

### ISSUE THREAD

**Issue by jasperSpeicher** [NicolasSiver/nodebb-plugin-ns-custom-fields#21]
OSX, custom fields version 5.0.1
I have tried with node 8.1.4 and 9.6.1, and I keep getting this after installing and running the build script for the acp, yet the file in question has not been changed:

```
jasperspeicher:acp jjs$ npm run build

> custom-fields-admin-panel@1.0.0 build /Users/jjs/Documents/Business/AWE/awe-member-directory/nodebb-plugin-ns-custom-fields/client/acp
> NODE_ENV=production browserify index.js -g [envify --NODE_ENV 'production'] -t [ babelify --presets [ es2015 react ] ]| uglifyjs -c -m > ../../public/js/acp.js

TypeError: /Users/jjs/Documents/Business/AWE/awe-member-directory/nodebb-plugin-ns-custom-fields/client/acp/index.js: _esutils2.default.keyword.isReservedWordES6 is not a function
    at Object.isValidIdentifier (/Users/jjs/Documents/Business/AWE/awe-member-directory/nodebb-plugin-ns-custom-fields/client/acp/node_modules/babel-types/lib/validators.js:167:61)
    at toIdentifier (/Users/jjs/Documents/Business/AWE/awe-member-directory/nodebb-plugin-ns-custom-fields/client/acp/node_modules/babel-types/lib/converters.js:210:10)
    at Object.toBindingIdentifierName (/Users/jjs/Documents/Business/AWE/awe-member-directory/nodebb-plugin-ns-custom-fields/client/acp/node_modules/babel-types/lib/converters.js:218:10)
    at exports.default (/Users/jjs/Documents/Business/AWE/awe-member-directory/nodebb-plugin-ns-custom-fields/client/acp/node_modules/babel-helper-function-name/lib/index.js:41:12)
    at PluginPass.ObjectProperty (/Users/jjs/Documents/Business/AWE/awe-member-directory/nodebb-plugin-ns-custom-fields/client/acp/node_modules/babel-plugin-transform-es2015-function-name/lib/index.js:20:63)
    at newFn (/Users/jjs/Documents/Business/AWE/awe-member-directory/nodebb-plugin-ns-custom-fields/client/acp/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/jjs/Documents/Business/AWE/awe-member-directory/nodebb-plugin-ns-custom-fields/client/acp/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/jjs/Documents/Business/AWE/awe-member-directory/nodebb-plugin-ns-custom-fields/client/acp/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/jjs/Documents/Business/AWE/awe-member-directory/nodebb-plugin-ns-custom-fields/client/acp/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/jjs/Documents/Business/AWE/awe-member-directory/nodebb-plugin-ns-custom-fields/client/acp/node_modules/babel-traverse/lib/context.js:150:16)
```

**Comment by NicolasSiver** [comment]
Hello.

The plugin does not require to build ACP in order to work. Why do you try to compile the ACP?

**Comment by FaizanZahid** [comment]
@jasperSpeicher  r u trying to run this plugin on node bb 1.9.x ?

**Comment by FaizanZahid** [comment]
@NicolasSiver  when i try to install it, i cannot find this plugin on my ACP, i m on node bb 1.9.2,

does that mean its not compatible with latest ver? 

![image](https://user-images.githubusercontent.com/9073066/40431338-2328e8fc-5e9f-11e8-9bc6-4f5249a1fd9a.png)
