### ISSUE TITLE
ACP Will Not Load

### ISSUE THREAD

**Issue by balag12** [NicolasSiver/nodebb-plugin-ns-custom-fields#34]
Trying to navigate to admin/plugins/custom-fields leads to this error message:
![image](https://i.imgur.com/BGhZ7eG.png)

I am using the latest version of the plugin available in NodeBB v1.12.2. In addition, the following error messages appear on restart:
```2019-08-28T14:24:19.767Z [4567/8025] - [33mwarn[39m: [deprecated] requiring core modules with `module.parent.require('./src/emitter')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /home/forum/NodeBB-1.12.2/node_modules/nodebb-plugin-ns-custom-fields/plugin/nodebb.js:9:31
2019-08-28T14:24:19.769Z [4567/8025] - [31merror[39m: Error: Cannot find module './src/emitter'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Module.require.main.require (/home/forum/NodeBB-1.12.2/require-main.js:8:10)
    at /home/forum/NodeBB-1.12.2/node_modules/nodebb-plugin-ns-custom-fields/plugin/nodebb.js:9:31
    at Object.<anonymous> (/home/forum/NodeBB-1.12.2/node_modules/nodebb-plugin-ns-custom-fields/plugin/nodebb.js:47:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
2019-08-28T14:24:19.770Z [4567/8025] - [33mwarn[39m: [plugins] Unable to parse library for: nodebb-plugin-ns-custom-fields```

**Comment by liuderchi** [comment]
@balag12 In my case this issue could be solved if you manually __install latest version (v6.0.0) via NPM__.
Currently I found that nodebb DOES NOT provide you latest version (v5.1.0)
cc @NicolasSiver 

![Screen Shot 2020-02-15 at 9 18 52 PM](https://user-images.githubusercontent.com/4994705/74588609-e34bae80-5038-11ea-924c-74fd06accdb7.png)
(tested locally with latest nodebb build on macOS)
