### ISSUE TITLE
Issue on loading on nodeBB 1.16.2

### ISSUE THREAD

**Issue by rgigante** [NicolasSiver/nodebb-plugin-ns-custom-fields#43]
I've recently installed ns-custom-fields on nodeBB 1.16.2 and I'm hitting a loading issue as from the log below
```
2021-03-30T12:37:58.105Z [4568/23965] - error: Error: Cannot find module './src/emitter'
Require stack:
- /home/standarduser/backstage_prd/require-main.js
- /home/standarduser/backstage_prd/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Module.require.main.require (/home/standarduser/backstage_prd/require-main.js:8:10)
    at /home/standarduser/backstage_prd/node_modules/nodebb-plugin-ns-custom-fields/plugin/nodebb.js:9:31
    at Object.<anonymous> (/home/standarduser/backstage_prd/node_modules/nodebb-plugin-ns-custom-fields/plugin/nodebb.js:47:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
2021-03-30T12:37:58.105Z [4568/23965] - verbose: [plugins] Could not load plugin : nodebb-plugin-ns-custom-fields
```
is it a known problem?

**Comment by Jafesu** [comment]
I am having the same issue on 1.18.6.

NodeBB no longer has an emitter.js file

**Comment by vgmoose** [comment]
The latest version of this plugin on [npm.js is 6.0.0](https://www.npmjs.com/package/nodebb-plugin-ns-custom-fields), but the one reported as latest by the nodebb UI is 5.1.0. There was a [commit that removes emitter](https://github.com/NicolasSiver/nodebb-plugin-ns-custom-fields/commit/0888143f3d986e6b40c5c6b0aa3321a83f080fdd) between these two versions.

However, manually trying to update to 6.0.0 using `npm install nodebb-plugin-ns-custom-fields@6.0.0` results in a build-time error (preventing start up):
```
error: Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (/usr/src/app/node_modules/express/lib/router/route.js:202:15)
    at Function.proto.<computed> [as get] (/usr/src/app/node_modules/express/lib/router/index.js:516:19)
    at Object.helpers.setupPageRoute (/usr/src/app/src/routes/helpers.js:32:9)
    at Module.setup (/usr/src/app/node_modules/nodebb-plugin-ns-custom-fields/plugin/routes.js:31:22)
    at /usr/src/app/node_modules/nodebb-plugin-ns-custom-fields/node_modules/async/dist/async.js:66:19
    at /usr/src/app/node_modules/nodebb-plugin-ns-custom-fields/node_modules/async/dist/async.js:3880:24
    at replenish (/usr/src/app/node_modules/nodebb-plugin-ns-custom-fields/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/usr/src/app/node_modules/nodebb-plugin-ns-custom-fields/node_modules/async/dist/async.js:995:17)
    at /usr/src/app/node_modules/nodebb-plugin-ns-custom-fields/node_modules/async/dist/async.js:969:16
    at /usr/src/app/node_modules/nodebb-plugin-ns-custom-fields/node_modules/async/dist/async.js:3885:13
```
